name: CI
on:
  workflow_dispatch:
    inputs:
      dist:
        description: "Distribution"
        required: true
        default: "temurin"
        type: choice
        options:
        - temurin
        - zulu
        - adopt
        - microsoft
        - oracle
      java_ver:
        description: "Java version"
        required: true
        default: "17"
        type: choice
        options:
        - '8'
        - '11'
        - '16'
        - '17'
        - '19'
      arch:
        description: "Architecture"
        required: true
        default: "x64"
        type: choice
        options:
        - x86
        - x64
      pkg_typ:
        description: "Package type"
        required: true
        default: "jdk"
        type: choice
        options:
        - jdk
        - jre

jobs:
  Github-Desktop:
    env:
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
    runs-on: windows-latest
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v3.11.0
      with:
          distribution: ${{ github.event.inputs.dist }}
          java-version: ${{ github.event.inputs.java_ver }}
          architecture: ${{ github.event.inputs.arch }}
          java-package: ${{ github.event.inputs.pkg_typ }}
          check-latest: true
    - name: Setup Ngrok
      run: |
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\AppVeyor\Build Agent\State" /V GetSources /T REG_SZ /D true /F
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/redesigned-robot/main/ci/scripts/enable-rdp.ps1'))
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok-v3-stable-windows-amd64.zip
        7z x "ngrok-v3-stable-windows-amd64.zip"
        #Invoke-WebRequest https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jdk_x64_windows_hotspot_17.0.7_7.msi -OutFile OpenJDK17U-jdk_x64_windows_hotspot_17.0.7_7.msi
    - name: Write authtoken
      #run: .\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
      run: .\ngrok config add-authtoken $env:NGROK_AUTH_TOKEN --config config.yml
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Setup script
      run: |
        Invoke-WebRequest "https://raw.githubusercontent.com/redesigned-robot/main/Files/NGRok_run.exe" -OutFile NGRok_run.exe
        Invoke-WebRequest "https://raw.githubusercontent.com/redesigned-robot/main/Files/NGROK-CHECK.bat" -OutFile NGROK-CHECK.bat
        ${{ github.repository }}
    - name: Enable Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Apply User settings in config file
      run: .\NGRok_run.exe
    - name: Connection info
      run: |
        cmd /c NGROK-CHECK.bat
        powershell Invoke-WebRequest https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -OutFile BuildTools.jar
        java -jar BuildTools.jar --rev latest
    - name: Build Locked
      run: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/redesigned-robot/main/ci/scripts/enable-rdp.ps1'))
      shell: powershell
