name: Main

on:
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      full_sha_output: ${{ steps.var.outputs.full_sha }}
      short_sha_output: ${{ steps.var.outputs.short_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - id: var
        run: |
          echo "full_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
  result:
    runs-on: ubuntu-latest
    needs: runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
        env:
          OUTPUT1: ${{needs.runner.outputs.full_sha_output}}
          OUTPUT2: ${{needs.runner.outputs.short_sha_output}}
          
      - run: |
          echo "$OUTPUT1 $OUTPUT2"
          echo $OUTPUT1 $OUTPUT2
          echo "v20.11 - Back from the Dead [${{ needs.runner.outputs.short_sha_output }}]"
          echo v20.11 - Back from the Dead [${{ needs.runner.outputs.short_sha_output }}]
          echo "v20.11 - Back from the Dead [${{ needs.runner.outputs.full_sha_output }}]"
          echo v20.11 - Back from the Dead [${{ needs.runner.outputs.full_sha_output }}]
          echo "${{ needs.runner.outputs.short_sha_output }}"
          echo ${{ needs.runner.outputs.short_sha_output }}
          echo "${{ needs.runner.outputs.full_sha_output }}"
          echo ${{ needs.runner.outputs.full_sha_output }}

      - name: Delete tag and release
        uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: "1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Test [${{ needs.runner.outputs.short_sha_output }}]
          tag: "1.0"
          body: |
            $OUTPUT1 $OUTPUT2
          artifacts: |
            README.md
